# Generated by Django 5.0.7 on 2024-12-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_alter_todo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="board",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board",
                to="board.board",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="column",
                to="board.column",
            ),
        ),
    ]
