# Generated by Django 5.0.7 on 2024-12-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_remove_column_board_alter_todo_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
