# Generated by Django 5.0.7 on 2024-12-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_todo_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="order",
            field=models.PositiveIntegerField(),
        ),
    ]
